Reduce comparison overhead of logging window
metabrainz/picard pull request #1766
Opened 2021-03-23 17:15 UTC by Gabrielcarvfer

# Summary

* This is a…
    * [ ] Bug fix
    * [ ] Feature addition
    * [x] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**:
Calculate the starting position of log entries to print in the log window instead of comparing individual positions.

# Problem

* JIRA ticket (_optional_): PICARD-XXX

The logging window drastically slows down Picard on Windows (at least on debug mode). The cause of the slowdown is the comparison of positions of entries that should be printed in the queue log. 

# Solution

Instead of comparing each item, calculate the starting position and copy everything available after that.

# Action

2021-03-23 17:18 UTC, Gabrielcarvfer commented
Should I include a test? 
<details>
<summary>
I've tested with this:
</summary>

```
from collections import deque

class Item():
    _log_queue = deque(maxlen=10)

    def __init__(self, pos=0):
        self.pos = pos

    @staticmethod
    def contents(prev=-1):
        # If last item position > deque maxlen, we are not using absolute numbers anymore
        last_pos = Item._log_queue[-1].pos
        if last_pos >= Item._log_queue.maxlen:
            offset = (prev + last_pos + 2) % Item._log_queue.maxlen
        else:
            offset = prev+1
        contents = [Item._log_queue[i] for i in range(offset, len(Item._log_queue))]
        return contents

    @staticmethod
    def push(item):
        Item._log_queue.append(item)

for i in range(8):
    Item.push(Item(i))
list = Item.contents()
if list[0].pos == 0 and list[-1].pos == 7:
    print("OK")
else:
    exit(-1)

for i in range(8, 15):
    Item.push(Item(i))
list2 = Item.contents(list[-1].pos)
if list2[0].pos == 8 and list2[-1].pos == 14:
    print("OK")
else:
    exit(-2)

for i in range(15, 20):
    Item.push(Item(i))
list3 = Item.contents(list2[-1].pos)
if list3[0].pos == 15 and list3[-1].pos == 19:
    print("OK")
else:
    exit(-3)
```
</details>

2021-03-23 17:34 UTC, Gabrielcarvfer commented
Do not merge. Just found a weird edge case. Reworking it. :)

2021-03-23 19:28 UTC, phw commented
Good one, that part of code clearly needs some refactoring. Looking forward to your updated patch.

> Should I include a test?

Yes, having tests for this would be really good. The logic is tricky and can easily break on future changes.

2021-03-23 21:05 UTC, Gabrielcarvfer commented
> Yes, having tests for this would be really good. The logic is tricky and can easily break on future changes.
Done. It is clearer, faster and rock solid (assuming the positions are monotonically increasing).
Not sure why the tests didn't work here, worked just fine locally. Looking into it. ._.

2021-03-23 21:13 UTC, Gabrielcarvfer commented
OK, never reuse variables between tests.

2021-03-24 06:40 UTC, Gabrielcarvfer commented
Still thinking on the discontinuation issue. 

If there is a missing position in the deque (e.g. [5, 10, 11]), the offset calculation would return a negative number (prev=4, offset=len-(last-prev)=3-[11-4]=-4), which is completely wrong as 4 is prev of 5, which is in offset=0).

Maybe putting something similar to the old code as a slow path in case offset < 0 (which indicates the discontinuation).

2021-03-24 08:55 UTC, phw requested changes
This works great and looks good to me. Only minor comments.

> If there is a missing position in the deque (e.g. [5, 10, 11]), the offset calculation would return a negative number

That actually should never happen, am I right? As I understand we have a single deque with upcounting positions, and nothing can be removed in between anyway.

But if we want the code to be more robust even in case of changes to the rest of the code a check like you suggested could be added.

2021-03-24 08:55 UTC, phw commented on picard/log.py
> +            contents = [self._log_queue[i] for i in range(*bounds)]
I think we could make this an iterator:

    (self._log_queue[i] for i in range(*bounds))

`contents` only gets used to iterate over it afterwards, so we don't really need to create a list here.

2021-03-24 08:55 UTC, phw commented on test/test_log.py
> +            Item.push(Item(i))
The tests all use a single global `deque`. I'd rather have a separate instance created in `setup()` for this to initialize a fresh instance for each test. That also removes the need for each test to run `Item.clear()`.

2021-03-24 09:30 UTC, phw commented
I added PICARD-2157

@zas you implemented most of the current logic, what is your opinion of the continuation thing? Should it be handled?

2021-03-24 23:20 UTC, zas commented
> I added [PICARD-2157](https://tickets.metabrainz.org/browse/PICARD-2157)
> 
> @zas you implemented most of the current logic, what is your opinion of the continuation thing? Should it be handled?

Well, as said, it shouldn't happen. It would be safer to handle it, if we can find a simple enough way to do it.

2021-03-25 02:59 UTC, Gabrielcarvfer commented
<details>
<summary>
Looks terrible.
</summary>

```
def _get_log_contents(previous_position, log_queue):
    # If log queue is empty, return empty list
    if len(log_queue) == 0:
        return []

    first_position = log_queue[0].pos

    # If first item of the queue is bigger than prev, use first item position - 1 as prev
    # e.g. queue = [8, 9, 10] , prev = 6, new_prev = 8-1 = 7
    if previous_position < first_position:
        previous_position = first_position - 1

    last_position = log_queue[-1].pos

    # If the last position is smaller than the previous position, nothing useful in the queue
    if last_position < previous_position:
        return []

    queue_length = len(log_queue)

    # The offset of the first item in the queue is
    # equal to the length of the queue, minus the length to be printed
    offset = queue_length - (last_position - previous_position)

    # If offset is negative, there is a discontinuation in the log queue and we take the slow path
    if offset < 0:
        i = 0
        for queue_item in log_queue:
            if queue_item.pos > previous_position:
                offset = i-1
                break
    return (log_queue[i] for i in range(offset, queue_length))
```
</details>

<details>
<summary>
I much prefer doing something like this.
</summary>

```
def _calculate_bounds(previous_position, first_position, last_position, queue_length):
    # If first item of the queue is bigger than prev, use first item position - 1 as prev
    # e.g. queue = [8, 9, 10] , prev = 6, new_prev = 8-1 = 7
    if previous_position < first_position:
        previous_position = first_position-1

    # The offset of the first item in the queue is
    # equal to the length of the queue, minus the length to be printed
    offset = queue_length - (last_position - previous_position)

    # If prev > last_position, offset will be bigger than queue length offset > queue_length
    # This will force an empty list
    if offset > queue_length:
        offset = queue_length

    # If offset < 1, there is a discontinuity in the queue positions
    # Setting queue_length to 0 informs the caller that something is wrong and the slow path should be taken
    if offset < 0:
        queue_length = 0
    return offset, queue_length


    [...]

    def contents(self, prev=-1):
        with self._queue_lock:
            # If log queue is empty, return
            if len(self._log_queue) == 0:
                return []
            bounds = _calculate_bounds(prev, self._log_queue[0].pos, self._log_queue[-1].pos, len(self._log_queue))

            if not bounds[1]:
                # Take the slow path
                bounds = [0, len(self._log_queue)]
                for i, queue_item in enumerate(self._log_queue):
                    if queue_item.pos > prev:
                        bounds[0] = i-1
                        break
            contents = (self._log_queue[i] for i in range(*bounds))
        return contents
```
</details>

2021-03-25 07:24 UTC, phw commented
What about

```python
    def contents(self, prev=-1):
        with self._queue_lock:
            if len(self._log_queue) == 0:
                return []
            offset, length = _calculate_bounds(prev, self._log_queue[0].pos, self._log_queue[-1].pos, len(self._log_queue))
            if offset >= 0:
                contents = (self._log_queue[i] for i in range(offset, length))
            # If offset < 1, there is a discontinuity in the queue positions
            # Use a slower approach to get the new content.
            else:
                contents = (x for x in self._log_queue if x.pos > prev)
        return contents
```

Leaving `_calculate_bounds`  as is and handling the special case as we did before. In both cases it's an iterator.

2021-03-25 11:25 UTC, Gabrielcarvfer commented
Changing variables name is fine, and makes clearer. I was thinking more if using the length as a flag would be ok, or you would prefer an exception.

The problem is in the slow path. I've seen 17k items in the queue, and the OG code (also used in your suggestion) would check item by item, usually to get only the a few items in the end of the queue. 

I was thinking of using binary search  to make the slow path faster (assuming items are at the very least sorted).

2021-03-25 18:32 UTC, phw commented
As this is for a case we expect to never happen I would not overcomplicate it. If this was some other code I would actually say that it should fail and log an error.

Since we are in error logging code here it probably is a good idea to still continue, as error logging is something you especially want in case of a bug. But IMHO it is more useful to keep the code real simple for the unexpected case.

2021-03-26 19:08 UTC, Gabrielcarvfer commented
For the most part, it should be quite a bit faster.
I was looking at related stuff, and found this
```
        fmt = self.textCursor.blockCharFormat()
        self.textCursor.setBlockCharFormat(self._format(logitem.level))
        super()._add_entry(logitem)
        self.textCursor.setBlockCharFormat(fmt)  # is this format really necessary? didn't seem to change anything when commented out, at least on Windows
        ```

2021-03-26 19:31 UTC, zas commented
> For the most part, I think this is done. However I started looking at related stuff, and found this
> 
> ```
> fmt = self.textCursor.blockCharFormat()
> self.textCursor.setBlockCharFormat(self._format(logitem.level))
> super()._add_entry(logitem)
> self.textCursor.setBlockCharFormat(fmt)  # is this format really necessary? didn't seem to change anything when commented out, at least on Windows
> ```

I think it is needed to revert to normal format after the change to `self._format(logitem.level)`

2021-03-26 19:39 UTC, Gabrielcarvfer commented
> I think it is needed to revert to normal format after the change to `self._format(logitem.level)`

But doesn't it get updated per logitem.level? So if the next item has a different level, it will switch to the correct one and print, then the next logitem will do the same, etc. Should be fine if all logitems have their own format.

2021-03-26 22:00 UTC, zas commented
Yes, it could probably be optimized, we could even skip changing format if not strictly needed.

2021-03-27 03:03 UTC, Gabrielcarvfer commented
<details>
<summary>
With double SetCharBlockFormat
</summary>

![pre_format_changes](https://user-images.githubusercontent.com/1678454/112708161-3d9b7d80-8e8f-11eb-8a82-e27428ace708.png)
</details>

<details>
<summary>
Only call SetCharBlockFormat if logitem.level is different from the previous item
</summary>

![post_format_changes](https://user-images.githubusercontent.com/1678454/112708181-57d55b80-8e8f-11eb-8755-6be0a747a73a.png)
![post_format_change_setBlockCharFormat](https://user-images.githubusercontent.com/1678454/112708184-5ad04c00-8e8f-11eb-8d7c-65c2cd8a0489.png)
</details>

14k calls down to 11 seems like a win to me, even though I have no idea how to measure responsiveness of anything. Nothing seems to have changed.

2021-03-27 18:56 UTC, phw approved these changes
Looks great to me. Good catch with the format change. This reduction of calls definitely makes sense.

2021-03-28 09:19 UTC, zas requested changes
Looks good to me, just minor comments.

2021-03-28 09:19 UTC, zas commented on picard/ui/logview.py
> +        self._prev_logitem_level = logitem.level
What about:

```python
        if self._prev_logitem_level != logitem.level:
            self.textCursor.setBlockCharFormat(self._format(logitem.level))
            self._prev_logitem_level = logitem.level
        super()._add_entry(logitem)
```

2021-03-28 09:19 UTC, zas commented on test/test_log.py
> +        if len(self._log_queue) == 0:
It could be written in a more pythonic form:

```python
if not self._log_queue:
    return []
```

2021-03-28 09:19 UTC, zas commented on test/test_log.py
> +        return contents
Since both branches set `contents`, we could just `return` directly (dropping variable)

2021-03-28 09:19 UTC, zas commented on test/test_log.py
> +class Item:
We already have a class named `Item` [elsewhere](https://github.com/metabrainz/picard/blob/4e13a1835d1f97cd381204f11eb33c16f241e558/picard/ui/item.py#L30), perhaps use another name.

2021-03-28 18:34 UTC, Gabrielcarvfer commented on test/test_log.py
> +class Item:
Changed to TestLogItem. Should be better. :)

2021-03-28 18:35 UTC, Gabrielcarvfer commented on test/test_log.py
> +        return contents
Sure. I usually try to keep a single point of exit to simplify measurements and debugging.

2021-03-28 18:35 UTC, Gabrielcarvfer commented on test/test_log.py
> +        if len(self._log_queue) == 0:
Done.

2021-03-28 22:42 UTC, zas approved these changes

2021-03-29 06:28 UTC, phw approved these changes
We'll merge this for 2.6.1 after the 2.6 release

2021-04-01 19:47 UTC, merged