PICARD-2161: Add function to remove duplicate entries from multi-value variable
metabrainz/picard pull request #1769
Opened 2021-03-27 17:48 UTC by rdswift

# Summary

* This is a…
    * [ ] Bug fix
    * [x] Feature addition
    * [ ] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**:  This adds a new scripting function `$uniquemulti()` to remove duplicate items from a multi-value variable.

# Problem

Duplicate items can be created in a multi-value variable when combining lists such as genres.  There is no easy way to remove duplicate entries.

* JIRA ticket (_optional_): PICARD-2161

# Solution

Add a new scripting function `$uniquemulti()` to remove duplicate entries.  Include an option to do case-sensitive comparisons.

# Action

Note to update the Picard documentation to include this new function.

2021-03-27 19:50 UTC, rdswift commented
Would this be better if I used the `picard.util.uniquify()` function, and dropped the ability for case-insensitive comparisons?

2021-03-28 09:33 UTC, zas commented
> Would this be better if I used the `picard.util.uniquify()` function, and dropped the ability for case-insensitive comparisons?

Nope, code looks good as is to me.

2021-03-28 09:35 UTC, zas requested changes

2021-03-28 09:35 UTC, zas commented on picard/script/functions.py
> +    return multi_value.separator.join(sorted(list(set(multi_value))))
`sorted(list(set(...)))` -> `sorted(set(...))`

2021-03-28 13:35 UTC, phw commented
Could we get away with just $unique instead of $uniquemulti or would that be unclear?

For me I would always expect a function $unique to work on a list of things.

2021-03-28 17:49 UTC, rdswift commented
> Could we get away with just $unique instead of $uniquemulti or would that be unclear?
> 
> For me I would always expect a function $unique to work on a list of things.

I'm okay with changing it to just `$unique`.  That actually makes more sense.

2021-03-29 14:07 UTC, zas approved these changes

2021-03-29 14:21 UTC, phw approved these changes

2021-04-01 20:08 UTC, merged