PICARD-2150: Allow user to hide metadata view
metabrainz/picard pull request #1779
Opened 2021-04-02 15:59 UTC by phw

# Summary

* This is a…
    * [ ] Bug fix
    * [x] Feature addition
    * [ ] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem

* JIRA ticket (_optional_): PICARD-2150

The metadata view can take quite a lot of space, especially on small screens. While it can be resized sometimes it would be good to have it out of view. In the past users could completely hide it by dragging it down. We disabled this as users accidentally lost access to this view without a proper UI hint how to get it back.

# Solution
Add an action to the View menu to show/hide the metadata view, together with a keyboard shortcut.

# Action

2021-04-02 16:48 UTC, zas requested changes
A nice improvement :)

2021-04-02 16:48 UTC, zas commented on picard/ui/mainwindow.py
> +            self.metadata_view.hide()
I think you can replace the whole `if/else` with:

```python
self.metadata_view.setVisible(show)
```

2021-04-02 16:48 UTC, zas commented on picard/ui/mainwindow.py
> +        """Show/hide the cover art box."""
Update the comment as it hides the whole metadata box

2021-04-02 17:28 UTC, Sophist-UK commented
I haven't had the chance to check the code, but for performance reasons do make sure that the metadata window is not updated when you change selections if it is hidden, and ensure that the metadata is updated to match selections when you make it visible again.

2021-04-02 17:49 UTC, phw commented
Good point. The current patch does not prevent updates, but we could keep updates to both metadata and cover art while the view is hidden. I'll update the PR

2021-04-03 13:56 UTC, phw commented
I implemented skipping updating the metadata view and cover art box if they are hidden. This actually would already have been useful previously for the cover art box only. Now it skips updating both the metadata view and the cover art box accordingly.

2021-04-06 16:34 UTC, zas approved these changes

2021-04-07 13:19 UTC, merged