PICARD-2208: Allow resizing the "Before" and "After" columns in file naming examples
metabrainz/picard pull request #1815
Opened 2021-05-12 17:34 UTC by rdswift

# Summary

* This is a…
    * [ ] Bug fix
    * [ ] Feature addition
    * [ ] Refactoring
    * [x] Minor / simple change (like a typo)
    * [x] Other
* **Describe this change in 1-2 sentences**: Adds a splitter bar to allow resizing the "Before" and "After" columns in the file naming examples.  Also removes two unused layout widgets.

# Problem

The "Before" and "After" file naming example columns are fixed width on the Options --> File Naming screen, but they are sizable on the script editor screen.  This is inconsistent, and doesn't allow the same flexibility.

* JIRA ticket (_optional_): PICARD-2208

# Solution

Add a splitter bar to allow resizing the "Before" and "After" columns in the file naming examples on the Options --> File Naming screen.

# Action

None.

2021-05-12 18:19 UTC, phw requested changes
The file naming script combo box behaves strange, I think the QGroupBox it is using is not needed here:

![grafik](https://user-images.githubusercontent.com/29852/118023321-b5e5d180-b35d-11eb-9daf-8a94f3dabb27.png)

A label followed by a QComboBox would be sufficient.

Also the Before / After columns look slightly different in the filenaming option pages and the scripting dialog. In the options page there is a separator also between the column headers, in the dialog there isn't. I think it looks a bit nicer in the dialog. I don't know exactly why it is different, but this is the dialog:

![grafik](https://user-images.githubusercontent.com/29852/118023836-4c19f780-b35e-11eb-9706-19a7c5d173f5.png)

And here is the same in the options:

![grafik](https://user-images.githubusercontent.com/29852/118023921-605df480-b35e-11eb-9cd3-efd0f64cff42.png)

Somehow there are more visible frames, that make this display look rather busy. I think the only difference is setting the two frames (left / right) to frameShape=NoFrame, otherwise I think the structure is the same.

Also setting the GroupBox for the filenaming examples to vertically MinimumExpanding gives the entire view a better behavior when resizing I think

2021-05-12 18:36 UTC, rdswift commented
@phw 

Agreed on all points and updated accordingly.  Thanks for catching them.

2021-05-13 08:17 UTC, zas approved these changes

2021-05-13 08:59 UTC, phw approved these changes

2021-05-13 09:00 UTC, merged

2021-05-13 09:00 UTC, phw commented
Thanks a lot