PICARD-2151: Add $year(), $month() and $day() helper functions to extract date info
metabrainz/picard pull request #1867
Opened 2021-07-21 18:37 UTC by rdswift

# Summary

* This is a…
    * [ ] Bug fix
    * [x] Feature addition
    * [ ] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**:  Add new `$year()`, `$month()` and `$day()` functions.

# Problem

* JIRA ticket (_optional_): PICARD-2151

Request for helper functions to extract the different parts of a date string.

# Solution

Add new `$year()`, `$month()` and `$day()` functions.

# Action

Reminder to update the documentation on https://github.com/rdswift/picard-docs/pull/104

2021-07-22 06:57 UTC, zas approved these changes
LGTM

2021-07-22 06:57 UTC, zas commented on picard/script/functions.py
> +        return parts[0], parts[1], parts[2]
We could use a `namedtuple` for the result.

```python
DateTuple = namedtuple('DateTuple', ('year', 'month', 'day'))

....

return DateTuple(parts[0], parts[1], parts[2])

```

So in caller functions, we can write:

```python
return _split_date(date_to_parse, date_order, separator).year
```

2021-07-22 07:03 UTC, phw reviewed
Great to have these functions :)

My only concern would be the date parsing, we now have different ways of interpreting the dates across the system. We have:

- [`picard.util.extract_year_from_date`](https://github.com/metabrainz/picard/blob/master/picard/util/__init__.py#L725), which uses [dateutil.parser.parse](https://dateutil.readthedocs.io/en/stable/parser.html#dateutil.parser.parse)
- [`picard.util.sanitize_date`](https://github.com/metabrainz/picard/blob/master/picard/util/__init__.py#L209) and some [other locations](https://github.com/metabrainz/picard/blob/master/picard/track.py#L425) where it just assumes `YYYY-MM-DD`

Maybe in this case it would be better to use [dateutil.parser.parse](https://dateutil.readthedocs.io/en/stable/parser.html#dateutil.parser.parse). We'd still want indicators to choose between the ymd, dmy and mdy orders, but dateutil.parser.parse has two parameter's `dayfirst` and `yearfirst` for this. We could keep your `ymd` etc. implementation, as I think this is easier to handle, but translate them to the boolean values:

|date_order|dayfirst|yearfirst|
|-|-|-|
|ymd|False|True|
|dmy|True|False|
|mdy|False|False|

2021-07-22 19:03 UTC, rdswift commented
I changed to using the `dateutil.parser.parse()` function as suggested, but there seems to be a problem.  When testing using an empty string or string of random characters as the date input, the exceptions are not being properly captured.  This only seems to happen in the test suite, and it seems to work properly in the script editor.  For now, I just deleted the tests for invalid dates, and added a check for an empty date string in the helper function.

Also, using the `dateutil` parser is a lot more forgiving with respect to missing elements, so I am using the default date of 1900-01-01 to provide the missing bits rather than returning an empty string in the `$year()`, `$month()` and `$day()` functions as before.  This bothers me a bit because the user can no longer check for example if the `release_date` contains just a year, a year and month, or a full date.  Is this okay, or do you have any suggestions?

2021-07-22 20:43 UTC, rdswift commented
Just ran into another issue...  There's currently no way to enter this into a script and save it using anything other than a hard-coded date because it shows the "Invalid date" error.  I'll have a look at fixing that.

2021-07-23 07:14 UTC, zas requested changes

2021-07-23 07:14 UTC, zas commented on picard/script/functions.py
> +    """`$countryname(country_code,translate="")`
This change is unrelated to this PR, I committed it as https://github.com/metabrainz/picard/commit/40a03a14f5df143e2831d3032f94d46f93306b6c

2021-07-23 07:24 UTC, phw commented
> This bothers me a bit because the user can no longer check for example if the `release_date` contains just a year, a year and month, or a full date. Is this okay, or do you have any suggestions?

Oh yes, the partial dates :( Those don't work well with dateutil, but are essential to our use case.

So probably better to go back to a custom implementation. I would be fine with what you previously had, that looked good function wise. In a follow up step we could then start extracting this logic to our own helper function and using this elsewhere where appropriate, completely replacing dateutil.

2021-07-23 07:26 UTC, zas requested changes

2021-07-23 07:26 UTC, zas commented on picard/script/functions.py
> +    yearfirst = date_order[0] == 'y'
The code above use 3 tests, and sets `date_order` to `ymd` while it isn't used afterwards.

I think following code is equivalent with less tests and sets:

```python
if date_order == 'dmy':
    dayfirst, yearfirst = True, False
elif date_order == 'mdy':
    dayfirst, yearfirst = False, False
else:  # defaults to 'ymd'
    dayfirst, yearfirst = False, True
```

What do you think?

2021-07-23 16:10 UTC, rdswift commented
Based on the discussion here and in IRC, I reverted the `dateutil` stuff, used a regular expression to split the date parts, and rebased against the `master` branch.

2021-07-23 16:37 UTC, zas requested changes
It looks good to me.

2021-07-23 16:37 UTC, zas commented on picard/script/functions.py
> +    parts = re.split('[^0-9]+', date_to_parse.strip())
Just a minor thing, we can use `\D` (=any non-digit) instead of `[^0-9]`:

```suggestion
    parts = re.split(r'\D+', date_to_parse.strip())
```

2021-07-23 17:41 UTC, zas approved these changes
Lgtm

2021-07-23 23:17 UTC, zas commented on picard/script/functions.py
> +"""
See https://github.com/metabrainz/picard/pull/1868#discussion_r675906402

2021-07-24 05:42 UTC, phw approved these changes

2021-07-24 08:32 UTC, zas approved these changes
LGTM

2021-07-24 08:32 UTC, merged