PICARD-2165: Add `is_multi()` function
metabrainz/picard pull request #1868
Opened 2021-07-23 18:15 UTC by rdswift

# Summary

* This is a…
    * [ ] Bug fix
    * [x] Feature addition
    * [ ] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**:  Add a new `$is_multi()` function.

# Problem

* JIRA ticket (_optional_): PICARD-2165

There is no way to check if a variable is a multi-value.  See discussion at https://community.metabrainz.org/t/function-variable-to-tell-whether-a-tag-containts-multiple-values/526594

# Solution

Add a new `$is_multi()` function to check if a variable is a multi-value with more than one element.

# Action

Reminder to update the documentation.

2021-07-23 23:15 UTC, zas requested changes

2021-07-23 23:15 UTC, zas commented on picard/script/functions.py
> +"""
When adding new function, I think we should always include Picard version it appeared.
As we did for example in https://github.com/metabrainz/picard/blob/89020eb8a14679ae2d677ea8d18b07873e9deb5d/picard/script/functions.py#L337

2021-07-24 08:31 UTC, zas submitted a review, later dismissed
LGTM

2021-07-24 08:50 UTC, rdswift commented
Rebased to address merge conflicts.

2021-07-24 09:02 UTC, zas approved these changes

2021-07-24 10:19 UTC, phw approved these changes

2021-07-24 10:23 UTC, phw approved these changes

2021-07-24 10:29 UTC, merged