PICARD-2246: Highlight items in Options dialog when profile is selected for output
metabrainz/picard pull request #1869
Opened 2021-07-23 22:53 UTC by rdswift

# Summary

* This is a…
    * [ ] Bug fix
    * [x] Feature addition
    * [ ] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [x] Other
* **Describe this change in 1-2 sentences**:  Add highlighting of options manged by the selected profile in the Options dialog.

# Problem

* JIRA ticket (_optional_): PICARD-2246

From the discussion:

> * The attached profiles dialog is not easy to understand. Great would be if we would have a UI that makes it clear inside the dialogs which options are being changed.

# Solution

Add highlighting of options manged by the selected profile in the Options dialog.

# Action

Reminder to update the documentation.

2021-07-24 10:37 UTC, phw commented
This is looking good. I like the generic approach, I was concerned that we would need to adapt each option dialog separately for something like this to work.

2021-07-24 12:43 UTC, rdswift commented
> This is looking good. I like the generic approach.

The one thing that's not so generic is that it requires each of the option dialogs to have their ui at `self.ui` so that there is a common starting point for finding the widgets to highlight.  Fortunately, this is the case for all of the existing option pages, but is something to bear in mind for any new pages added in the future.

2021-07-24 20:36 UTC, rdswift commented
Now that the basics are there, any suggestions for color combinations for the highlighting?  I'm thinking that we want something noticeable but not overwhelming, thus the reason for allowing different combinations for light and dark themes.

2021-07-24 20:54 UTC, rdswift commented
During my testing, I found that I often forgot to go back to the "User settings" target before saving changes to the theme, and only realized my mistake when I restarted Picard and the theme hadn't changed.  What do you think of having some sort of visual indicator on the dialog when a profile is selected as the output target?  I'm thinking perhaps a red border around the output target selector box when a profile is selected.  Another option would be to pop up a message reminding the user that the settings would only be saved to the profile and only for options managed by the profile.

2021-07-25 08:18 UTC, zas commented on picard/ui/options/dialog.py
> +                            style = highlight % opt_field
The highlight is great, though it isn't obvious it is related to Options profiles.
Would it be possible to add a tooltip?

2021-07-26 08:22 UTC, zas requested changes

2021-07-26 08:22 UTC, zas commented on picard/ui/options/dialog.py
> +                self.ui.save_to_profile.addItem(item["title"], item["id"],)
```suggestion
                self.ui.save_to_profile.addItem(item["title"], item["id"])
```

2021-07-26 08:22 UTC, zas commented on picard/ui/options/dialog.py
> +        highlight = "#%s { color: %s; background-color: %s; }"
`highlight` -> `highlight_fmt` ?
It would denote it's a format string.

2021-07-26 16:44 UTC, zas approved these changes
LGTM

2021-07-27 15:55 UTC, phw approved these changes
Really cool funtionality, thanks!

2021-07-27 15:55 UTC, merged

2021-07-28 15:38 UTC, rdswift commented
@phw,

> Really cool functionality, thanks!

Thanks, but this was really a team effort.  The ideas for highlighting the items and auto-selecting the first enabled profile came from discussions with you and @zas.