Rework additional files methods
metabrainz/picard pull request #1940
Opened 2021-11-09 17:05 UTC by zas

# Summary

* This is a…
    * [ ] Bug fix
    * [ ] Feature addition
    * [x] Refactoring
    * [ ] Minor / simple change (like a typo)
    * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem

* JIRA ticket (_optional_): PICARD-XXX

# Solution

# Action

2021-11-09 19:45 UTC, phw requested changes
The changes make sense. I'd just take the opportunity to add unit tests for the separate methods as well and hence keep the parameter chain.

2021-11-09 19:45 UTC, phw commented on picard/file.py
> +    def _get_additional_files_moves(self, old_path, new_path, config):
I'd keep the patterns passed as a parameter here. Then you also don't need to pass the config object and could have tests just for this method.

2021-11-09 19:45 UTC, phw commented on picard/file.py
> +        for old_file_path, new_file_path in self._get_additional_files_moves(old_path, new_path, config):
Same here, I'd keep the `moves` as a parameter. This method can be nicely tested, especially when you can easily pass a list of move entries. The method also doesn't care about whether `moves` is an iterator or a list, so this eases testing as well.

2021-11-09 20:07 UTC, zas commented
> The changes make sense. I'd just take the opportunity to add unit tests for the separate methods as well and hence keep the parameter chain.

I didn't add tests because main method is tested in https://github.com/metabrainz/picard/blob/master/test/test_filesystem.py
But I agree we could test each method individually

2021-11-09 20:37 UTC, phw approved these changes
Good job, LGTM

> I didn't add tests because main method is tested

Agreed, not really necessary. But the way the methods are now we could have test or also reuse them more easily if needed.

2021-11-09 20:45 UTC, zas commented
> > 
> 
> Agreed, not really necessary. But the way the methods are now we could have test or also reuse them more easily if needed.

I'll go a bit further, and add tests.

BTW, it is even easier to not pass `config` at all, see 93a8d83

2021-11-09 22:19 UTC, zas commented
I added more tests, some are a bit redundant, but difficult to avoid.
Overall code is simplified, and has better coverage.

2021-11-10 07:01 UTC, phw approved these changes
Great change. I like how it simplifies the tests and makes those more readable.

2021-11-10 07:02 UTC, merged