PICARD-2498: HTML escape plugin metadata before display in options
metabrainz/picard pull request #2117
Opened 2022-06-07 16:18 UTC by phw

# Summary

* This is a…
  * [x] Bug fix
  * [ ] Feature addition
  * [ ] Refactoring
  * [ ] Minor / simple change (like a typo)
  * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem

* JIRA ticket (_optional_): PICARD-2498

Currently all plugin metadata can potentially contain HTML which gets rendered when displaying the plugin details in options. This is not intentional, the only field that can currently contain HTML is the description.

This was revealed because the author list in the acousticbrainz plugin uses the format "Author Name <email>".

# Solution
HTML escape all plugin metadata fields except for the description.

For authors also try to detect the "Author Name <email>" and convert the author names into mailto links.

2022-06-07 17:54 UTC, zas requested changes

2022-06-07 17:54 UTC, zas commented on picard/ui/options/plugins.py
> +        re_author = re.compile(r"(?P<author>.*?)\s*<(?P<email>.*?)>")
In the email part, I think we should match `@` too.
It would avoid creating invalid mailto links for `some<thing>`.

2022-06-07 17:54 UTC, zas commented on picard/ui/options/plugins.py
> +    def link_authors(authors):
Write a test set for this method?

2022-06-07 17:54 UTC, zas commented on picard/ui/options/plugins.py
> +            match = re_author.match(author.strip())
```suggestion
            match = re_author.fullmatch(author.strip())
```

Else it will match stuff like `some<thing>else` (I think).

2022-06-08 19:17 UTC, phw commented
@zas I added the test and addressed your comments. Tests also revealed some issue with extra whitespace being added in case without e-mail.

2022-06-08 20:56 UTC, zas commented on test/test_ui_options_plugins.py
> +            PluginsOptionsPage.link_authors('Wile E. Coyote <coyote@acme.com>, Road <Runner>'),
I see an extra complication, those "mailbox" addresses can use double quotes (I think): "a,b" <x@y> can happen in a list of addresses.

Not sure it is worth bothering.

2022-06-08 22:00 UTC, phw commented on test/test_ui_options_plugins.py
> +            PluginsOptionsPage.link_authors('Wile E. Coyote <coyote@acme.com>, Road <Runner>'),
That should be handled already because quotes get escaped

2022-06-09 00:54 UTC, zas commented on test/test_ui_options_plugins.py
> +            PluginsOptionsPage.link_authors('Wile E. Coyote <coyote@acme.com>, Road <Runner>'),
Are you sure a comma inside double quotes is handled properly? I didn't test, but the `split(",")` may lead to an unexpected result.

2022-06-09 07:26 UTC, zas commented on test/test_ui_options_plugins.py
> +            PluginsOptionsPage.link_authors('Wile E. Coyote <coyote@acme.com>, Road <Runner>'),
What I suggest is testing this case:

```suggestion
            PluginsOptionsPage.link_authors('Wile E. Coyote <coyote@acme.com>, Road <Runner>, "a,b"<x@y>'),
```

Is it a valid case?

2022-06-09 11:39 UTC, zas commented on test/test_ui_options_plugins.py
> +            PluginsOptionsPage.link_authors('Wile E. Coyote <coyote@acme.com>, Road <Runner>'),
Yes, it would imply much complicated code, so let's not bother with that.

2022-06-09 11:39 UTC, zas approved these changes

2022-06-09 21:16 UTC, merged