`REMOVE_*` commands enhancements
metabrainz/picard pull request #2141
Opened 2022-09-04 20:34 UTC by skelly37

# Summary

* This is a…
  * [x] Bug fix
  * [x] Feature addition
  * [ ] Refactoring
  * [ ] Minor / simple change (like a typo)
  * [ ] Other
* **Describe this change in 1-2 sentences**:
Another batch of useful commands + patch to keep it strictly related to the removal procedure.

# Problem

The commands were left to do later but seemed useful to us

* JIRA ticket (_optional_): None

# Solution

1. Added 2 commands
2. Started using Tagger's methods

# Action

2022-09-04 20:48 UTC, rdswift commented
I suspect that the comments on lines 246-247 can be removed?

2022-09-05 15:57 UTC, skelly37 commented
Ping @phw @zas, fully done imo

2022-09-05 19:10 UTC, zas requested changes

2022-09-05 19:10 UTC, zas commented on picard/tagger.py
> +        for file in [x for x in self.iter_all_files() if argstring == x.filename]:
This double loop bothers me, isn't that equivalent to:

```python
for file in self.iter_all_files():
   if file.filename == argstring:
       self.remove([file])
       return
```

2022-09-06 06:05 UTC, zas requested changes

2022-09-06 06:05 UTC, zas commented on picard/tagger.py
> +        for album in [a for a in self.albums if a.iterfiles()]:
This code looks incorrect to me:
- Album.iterfiles() return an iterator, to evaluate if it has elements a conversion to a list is somehow needed
- the logic seems to be reversed, we want to remove empty albums/clusters

I think the following code is what we need (untested):

```python
for album in self.albums:
   if not any(album.iterfiles()):
       self.remove_album(album)

for cluster in self.clusters:
    if not any(cluster.iterfiles()):
            self.remove_cluster(cluster)
```

2022-09-06 15:18 UTC, zas approved these changes
LGTM

2022-09-07 06:05 UTC, zas approved these changes
LGTM

2022-09-07 06:56 UTC, phw approved these changes

2022-09-07 06:57 UTC, merged