PICARD-2558: Disable floatable toolbars on Wayland
metabrainz/picard pull request #2155
Opened 2022-09-26 20:30 UTC by phw

# Summary

* This is a…
  * [x] Bug fix
  * [ ] Feature addition
  * [ ] Refactoring
  * [ ] Minor / simple change (like a typo)
  * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem

* JIRA ticket (_optional_): PICARD-2558

Floatable toolbars are not fully supported by Qt, see https://bugreports.qt.io/browse/QTBUG-92191 . The user can make a toolbar floating, but it will always be displayed in the middle of the screen and cannot be moved by the user anymore (and also not docked again).

# Solution
On Wayland set `QToolBar.floatable`  to `False`

2022-09-26 21:06 UTC, zas requested changes
I think we should add a reference to upstream issue, as those changes may need to be removed once it will be solved.

2022-09-26 21:06 UTC, zas commented on picard/ui/mainwindow.py
> +            toolbar.setFloatable(False)
```suggestion
            toolbar.setFloatable(False)  # https://bugreports.qt.io/browse/QTBUG-92191
```

2022-09-26 21:06 UTC, zas commented on picard/ui/mainwindow.py
> +            toolbar.setFloatable(False)
```suggestion
            toolbar.setFloatable(False)  # https://bugreports.qt.io/browse/QTBUG-92191
```
```

2022-09-26 21:06 UTC, zas commented on picard/ui/mainwindow.py
> +            toolbar.setFloatable(False)
```suggestion
            toolbar.setFloatable(False)  # https://bugreports.qt.io/browse/QTBUG-92191
```
```

2022-09-26 21:27 UTC, phw commented
Yes, agreed. This is really a workaround. I committed your suggested changes.

2022-09-27 07:39 UTC, zas approved these changes
LGTM

2022-09-27 07:40 UTC, merged