Handle Qt drag and drop IgnoreAction
metabrainz/picard pull request #2271
Opened 2023-08-13 09:40 UTC by phw

# Summary

* This is a…
  * [ ] Bug fix
  * [ ] Feature addition
  * [x] Refactoring
  * [ ] Minor / simple change (like a typo)
  * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem

In places where Picard handles drag and drop handle the Qt `IgnoreAction`. See discussion at https://github.com/metabrainz/picard/pull/2270#pullrequestreview-1575294513

2023-08-13 18:08 UTC, Sophist-UK commented
As I said in my comment on the original PR, I was only guessing when IgnoreAction is used, but even without being able to create a use case where this happens, I think that ignoring the event and returning is a good way to go on this (rather than accept it as an actual drop event.

2023-08-13 20:53 UTC, phw commented
After additional testing I updated the PR. I think this now should actually work as expected.

The special handling of IgnoreAction is only performed inside the `dropEvent`. Only this influences which action is finally confirmed.

But also care needs to be taken to properly handle the `dragEnterEvent` and sometimes `dragMoveEvent`. This influences the user feedback shown to the user by changing the mouse cursor icon.

All our drops accept something that most closely can be considered a copy. E.g. dropping cover art does not move the cover art into Picard, but Picard gains a copy of the image data. Likewise dropping a plugin file does copy the plugin over to the plugin folder and attempting to initialize it.

Previously on Windows when dragging such files into Picard the mouse cursor would depend on the modifiers pressed. E.g. without a modifier it shows "copy", with shift it shows "move". By forcing the action to be copy in all cases the mouse cursor always shows the copy action. This avoids communicating a misleading action to the user.

2023-08-13 22:04 UTC, Sophist-UK commented
Excellent thinking Philipp. 😄

2023-08-14 08:15 UTC, zas requested changes

2023-08-14 15:43 UTC, zas approved these changes

2023-08-14 15:48 UTC, phw commented on picard/ui/itemviews.py
> +        if event.isAccepted() and (not event.source() or event.mimeData().hasUrls()):
Updated

2023-08-14 16:17 UTC, merged