PICARD-2468: Properly handle unspecified languages in ID3v2 comments
metabrainz/picard pull request #2370
Opened 2024-02-26 03:58 UTC by Serial-ATA

# Summary

* This is a…
  * [x] Bug fix
  * [ ] Feature addition
  * [ ] Refactoring
  * [ ] Minor / simple change (like a typo)
  * [ ] Other
* **Describe this change in 1-2 sentences**:
Picard no longer creates a duplicate `COMM` frame with the incorrect language when using `lang='XXX' + desc=''`.
# Problem

Previously, a `COMM` frame with `lang='XXX' desc=''` would be saved as a separate frame with `lang='eng' desc='XXX'`. This is due to Picard supporting both `comment:desc` and `comment:lang:desc` syntax for comment tags.

* JIRA ticket (_optional_): PICARD-2468

# Solution

A special case was added for `lang='XXX', desc=''`. I could not think of a better solution for the problem, as Picard normalizes all metadata keys. It would be more elegant if trailing colons were preserved.

# Action

Possibly explore storing these comments as `comment:XXX:`, leaving the trailing colon as a marker for an empty description. This solution is not perfect. In the event that someone has `comment:eng:XXX`, all `eng` comments are simply stored as `comment:desc`. With this change, their language would be overwritten with `XXX`.

2024-02-29 15:12 UTC, phw commented
Thanks a lot for this. I think as a workaround this probably makes sense and we could include it even in the next Picard 2.x release.

Essentially this is issue happens because the language notation got introduced as an afterthought (https://github.com/metabrainz/picard/commit/4d85c2e31fc0fe9dfd71f9e2989bf4a699bfa7be). Similar issues plague the still open PR #1650 for doing the same to the lyrics tag.

I guess we should reconsider this and make a harder cut for Picard 3, making the language not optional. I' thinking of having both colons be present even if language is empty, such as `comment::desc`. @zas what do you think?

2024-02-29 18:46 UTC, zas commented
> I guess we should reconsider this and make a harder cut for Picard 3, making the language not optional. I' thinking of having both colons be present even if language is empty, such as `comment::desc`.

Yes, I agree.

2024-03-01 00:13 UTC, phw requested changes
Ok, let's go with this. The code itself is good to go. Please only add a test for this case to https://github.com/metabrainz/picard/blob/master/test/test_util_tags.py#L37

Also please rebase this branch. CI is currently failing due to changes to the Github Action Windows image, and this has been fixed on the master branch.

2024-03-13 00:01 UTC, Serial-ATA commented
Hey @phw is there anything else I need to do for this?

2024-03-14 15:43 UTC, zas approved these changes
LGTM

2024-03-14 15:47 UTC, merged