Charset detection fixes
metabrainz/picard pull request #2375
Opened 2024-03-22 06:54 UTC by phw

# Summary

* This is a…
  * [x] Bug fix
  * [ ] Feature addition
  * [ ] Refactoring
  * [ ] Minor / simple change (like a typo)
  * [ ] Other
* **Describe this change in 1-2 sentences**:

# Problem

This fixes a couple of issues of charset-normalizer is not installed:

    - the utf-32-le BOM was in wrong order
    - longer BOMs need to be checked first
    - added BOM for utf-8-sig
    - skip test for windows-1251 detection (only available with charset-normalizer or chardet)

2024-03-22 09:21 UTC, zas requested changes

2024-03-22 09:21 UTC, zas commented on test/test_utils.py
> +                                 f'BOM {bom!r} dected as {encoding}, expected {expected_encoding}')
```suggestion
                                 f'BOM {bom!r} detected as {encoding}, expected {expected_encoding}')
```

2024-03-22 09:32 UTC, zas requested changes

2024-03-22 09:32 UTC, zas commented on test/test_utils.py
> +            b'\xff\xfe\00\00': 'utf-32-le',
Good catch ;=)

2024-03-23 16:48 UTC, phw commented on test/test_utils.py
> +                                 f'BOM {bom!r} dected as {encoding}, expected {expected_encoding}')
Fixed

2024-03-23 16:48 UTC, phw commented on test/test_utils.py
> +            b'\xff\xfe\00\00': 'utf-32-le',
Fixed, thanks

2024-03-23 18:36 UTC, phw commented
Minor addition to enable the multiline edit for the syncedlyrics tag: https://github.com/metabrainz/picard/commit/647fc3bd32f607d5868dda5614504cd207e9f8fa

Maybe we can improve this further in the future. Editing comments or lyrcis is still pretty awkward in Picard. And for synced lyrics we could even have a dedicated editor.

2024-03-23 20:56 UTC, zas approved these changes
LGTM

2024-03-27 12:37 UTC, zas commented
@Sophist-UK can you re-review this PR?

2024-03-28 10:42 UTC, Sophist-UK approved these changes
Apologies for missing this. LGTM

2024-03-28 11:52 UTC, merged