PICARD-1477: Option to never replace an image with a smaller one
metabrainz/picard pull request #2521
Opened 2024-07-04 14:19 UTC by twodoorcoupe

# Summary

* This is a…
  * [ ] Bug fix
  * [x] Feature addition
  * [ ] Refactoring
  * [ ] Minor / simple change (like a typo)
  * [ ] Other
* **Describe this change in 1-2 sentences**:
Adds an option in the "Cover Art" options page to never replace embedded cover art with smaller images of the same type.
# Problem

* JIRA ticket (_optional_): PICARD-1477

# Solution

At first I tried to implement this as a filter, but I hit a wall. So I had to move the logic inside `coverart/__init__.py`. Now when an image is downloaded, it checks if there was an image of the same type embedded into tags and if it was bigger.

I'm not entirely convinced by this solution either, in fact I'm still not sure how multiple images of the same type should be handled. For example, if a file has multiple "booklet" type images embedded, what size should I compare the downloaded image with? Maybe the minimum among images of the same type?

# Action

Additional actions required:
* [x] Update Picard [documentation](https://github.com/metabrainz/picard-docs) (please include a reference to this PR)
* [ ] Other (please specify below)

2024-07-04 14:58 UTC, rdswift commented
I'm not sure there is a "best" way to handle this with multiple images of the same type.  With your suggestion, I assume you mean "Maybe the minimum among *currently embedded* images of the same type"?  That's probably as good as any approach.  I certainly can't think of anything better right now.

A bit off topic perhaps, but...  What do you think of an option like "Never replace embedded images of this type:" to allow adding such an image if it doesn't exist, but not replace it (them) if an image of that type does exist?  The selection interface could be similar to the one used for the "Cover Art Archive" -> "Download only cover art images matching selected types" (possibly even reusing the same one with a slightly different note at the bottom):

![image](https://github.com/metabrainz/picard/assets/16990904/1d37aa18-4a58-4ee9-8929-6b513880aaa9)

As a side note, I really should fix the size of that window to decrease the minimum width.

2024-07-04 15:27 UTC, twodoorcoupe commented
>  With your suggestion, I assume you mean "Maybe the minimum among currently embedded images of the same type"?

Yes sorry, this is what I meant

>  What do you think of an option like "Never replace embedded images of this type:" to allow adding such an image if it doesn't exist, but not replace it (them) if an image of that type does exist?

I like the idea, this makes me think I should try to improve the possibilities for image filters. 

If I pass the `coverartimage` and `album` (or maybe just the previously embedded images to allow comparisons) to the filters, I would be able to frame both this pr and your proposal as image filters.

I think it would make it easier to add more features like these in the future too.

2024-07-05 09:32 UTC, zas commented on picard/util/imagelist.py
> +        return types_dict
With multiple images of same types dict values might be overwritten, not sure that's what we want.

2024-07-08 10:43 UTC, twodoorcoupe commented
> With multiple images of same types dict values might be overwritten, not sure that's what we want.

Now I made the dict keep track only of the smallest image for each type.

> The selection interface could be similar to the one used for the "Cover Art Archive" -> "Download only cover art images matching selected types" (possibly even reusing the same one with a slightly different note at the bottom):

For now I reused the same one, as I'm still trying to understand where it would be best to create a new one. 

I was thinking to create a new class that inherits from `CAATypesSelectorDialog` and only changes the labels' text, but I don't know where it would be more appropriate to put this class. 

Maybe inside the same file as the cover art options page?

2024-07-08 13:54 UTC, rdswift commented
> > The selection interface could be similar to the one used for the "Cover Art Archive" -> "Download only cover art images matching selected types" (possibly even reusing the same one with a slightly different note at the bottom):
> 
> For now I reused the same one, as I'm still trying to understand where it would be best to create a new one.
> 
> I was thinking to create a new class that inherits from `CAATypesSelectorDialog` and only changes the labels' text, but I don't know where it would be more appropriate to put this class.
> 
> Maybe inside the same file as the cover art options page?

Creating a new class should work, but I'm wondering if it would be simpler to use the same class but just change the appropriate label text when loading it?  In any case it may be appropriate to make some size adjustments to the existing dialog to decrease the width and allow expanding (vertically?) to accommodate text of different lengths.  I'm not sure I took into account different string lengths due to different language translations when I initially designed it.  I was pretty new to Python and the whole i18n stuff at the time.  If you think there's any value in that, I should be able to take a quick look at making it more flexible (in a separate PR).

2024-07-08 16:06 UTC, zas commented
> I was thinking to create a new class that inherits from `CAATypesSelectorDialog` and only changes the labels' text, but I don't know where it would be more appropriate to put this class.

Which text do you want to change?
Actually that's the `display()` method which is called, so you may may additional optional parameters to redefine stuff.

If you go for subclassing (which I'm ok with), you can do it directly where it is used.

2024-07-08 19:25 UTC, twodoorcoupe commented
> but I'm wondering if it would be simpler to use the same class but just change the appropriate label text when loading it?

> Actually that's the display() method which is called, so you may pass additional optional parameters to redefine stuff.

Ah that makes sense, thank you so much to both of you!

>  In any case it may be appropriate to make some size adjustments to the existing dialog to decrease the width and allow expanding (vertically?) to accommodate text of different lengths. I'm not sure I took into account different string lengths due to different language translations when I initially designed it.

I just tested it and the dialog seems to expand vertically automatically based on the size of the text, so I think there's no need to worry about that.

2024-07-08 20:05 UTC, rdswift commented
> > Actually that's the display() method which is called, so you may pass additional optional parameters to redefine stuff.
> 
> Ah that makes sense, thank you so much to both of you!

Have a look at https://github.com/metabrainz/picard/pull/2522.  This would allow you to specify the alternate instructions (both above and below the list boxes) in the call to the dialog.  It might be simpler than adding a new class.

2024-07-09 16:33 UTC, zas requested changes

2024-07-09 16:33 UTC, zas commented on picard/coverart/__init__.py
> +    def _set_metadata(self, coverartimage, data, info):
Maybe it would be a bit clear to use `image_info` instead of more generic `info`.
Same for all occurrences below

2024-07-09 16:33 UTC, zas commented on picard/util/imagelist.py
> +            types_dict[image.normalized_types()] = image
```suggestion
            types_dict[image_types] = image
```

2024-07-09 18:52 UTC, zas commented
> > > Actually that's the display() method which is called, so you may pass additional optional parameters to redefine stuff.
> > 
> > 
> > Ah that makes sense, thank you so much to both of you!
> 
> Have a look at #2522. This would allow you to specify the alternate instructions (both above and below the list boxes) in the call to the dialog. It might be simpler than adding a new class.

@twodoorcoupe @rdswift 's PR was merged, you can update this one.

2024-07-10 11:49 UTC, twodoorcoupe commented
Thank you @rdswift for the help!

2024-07-10 12:56 UTC, zas requested changes

2024-07-10 12:56 UTC, zas commented on picard/coverart/processing/__init__.py
> +def run_image_filters(data, info, album, coverartimage):
For the sake of consistency, please use `image_info` instead of `info`.

2024-07-10 12:56 UTC, zas commented on picard/coverart/processing/__init__.py
> +def run_image_processors(coverartimage, data, info):
For the sake of consistency, please use `image_info` instead of `info`.

2024-07-10 12:56 UTC, zas commented on picard/coverart/processing/__init__.py
> +        image = ProcessingImage(data, info)
For the sake of consistency, please use `image_info` instead of `info`.

2024-07-10 12:56 UTC, zas commented on picard/coverart/processing/filters.py
> +def size_filter(data, info, album, coverartimage):
For the sake of consistency, please use `image_info` instead of `info`.

2024-07-10 12:56 UTC, zas commented on picard/coverart/processing/filters.py
> +def bigger_previous_image_filter(data, info, album, coverartimage):
For the sake of consistency, please use `image_info` instead of `info`.

2024-07-10 12:56 UTC, zas commented on picard/coverart/processing/filters.py
> +def image_types_filter(data, info, album, coverartimage):
For the sake of consistency, please use `image_info` instead of `info`.

2024-07-10 12:56 UTC, zas commented on picard/const/defaults.py
> +DEFAULT_CA_NEVER_REPLACE_TYPE_EXCLUDE = ['matrix/runout', 'raw/unedited', 'watermark']
We should use tuples for those defaults (instead of lists).

2024-07-10 18:54 UTC, zas approved these changes
LGTM

2024-07-10 19:11 UTC, rdswift approved these changes
Looks good to me, too.  Nice work.

2024-07-12 06:40 UTC, phw approved these changes
Good work, LGTM

2024-07-12 07:31 UTC, merged